services:
  adguard-home-boost:
    container_name: adguard-home-boost
    image: xiebaiyuan/adguard-home-boost:latest
    restart: unless-stopped

    ports:
      - "49241:3080"  # 后端 API + 前端静态页面

    environment:
      - ADGH_URL=http://192.168.8.88
      - ADGH_USER=xiebaiyuan
      - ADGH_PASSWD=your_password
      - ADGH_SKIP_VERIFY=true
      - TZ=Asia/Shanghai

    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

    network_mode: bridge
